const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const layers=[],events=[],renders=[];let disposed=0;
class GraphicsLayer{constructor(){this.items=[];layers.push(this);}add(x){this.items.push(x);}addMany(x){this.items.push(...x);}removeAll(){this.items=[];}}
class Map{addMany(){}add(x){events.push(x);}remove(x){events.splice(events.indexOf(x),1);}destroy(){disposed++;}}
class SceneView{async when(){}async goTo(target,options){assert.equal(target.target.xmin,-122);assert.equal(target.target.xmax,-121);assert.equal(options.animate,false);}on(){return{remove(){disposed++;}};}async takeScreenshot(options){assert.equal(options.width,1200);assert.equal(options.height,800);return{dataUrl:'data:image/png;base64,checked'};}destroy(){disposed++;}}
class Value{constructor(value){Object.assign(this,value);}destroy(){disposed++;}}
const window={require:(names,ready)=>ready(Map,SceneView,Value,Value,GraphicsLayer,Value,Value,Value,Value)};
const sandbox={window,innerWidth:1440,setTimeout:()=>1,clearTimeout:()=>{},FireAtlasContext:{url:p=>'/demo/'+p},FireAtlasMap:{concentration:(_,c)=>c.weight,ramp:v=>{renders.push(v);return 'same-'+v;}},document:{createElement:()=>({}),head:{append(s){if(s.onload)s.onload();}}}};
vm.runInNewContext(fs.readFileSync('fireatlas/static/investigation-terrain.js','utf8'),sandbox);
(async()=>{const host={dataset:{}},renderer=await window.FireAtlasTerrain.mount(host,[-122,39,-121,40],()=>{});const frame={date:'2024-07-24',weighted:[],cells:[{cell_id:'1,2',sources:['MODIS_SP'],ring:[[0,0],[1,0],[1,1],[0,0]],weight:2,observed_days:3,modis_frp_max_mw:4}]};renderer.render(frame,{domain:4});renderer.render({...frame,date:'2024-07-25'},{domain:4});assert.deepEqual(renders,[.5,.5]);assert.equal(host.dataset.maximum,'4');renderer.context({product:'Dated raster',bounds:[-122,39,-121,40],path:'raster.png'});assert.equal(events.length,1);assert.equal(events[0].source[0].image,'/demo/raster.png');renderer.context(null);assert.equal(events.length,0);await renderer.capture();renderer.dispose();assert.equal(disposed,4);console.log('3D lifecycle: shared domain, dated context, bounded capture and listener disposal passed.');})().catch(e=>{console.error(e);process.exitCode=1;});
