import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {JSDOM} from 'jsdom';
import {createCanvas} from '@napi-rs/canvas';
import {sceneSkeletons} from './portable-scene.mjs';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost'});
for(const key of ['window','document','navigator','localStorage','Element','Node','HTMLElement','HTMLCanvasElement','Image','DOMParser'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
globalThis.requestAnimationFrame=(fn)=>setTimeout(fn,0);globalThis.cancelAnimationFrame=clearTimeout;
globalThis.devicePixelRatio=1;globalThis.matchMedia=()=>({matches:false,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){}});dom.window.matchMedia=globalThis.matchMedia;
globalThis.FontFace=class {constructor(family){this.family=family;this.status='loaded';} async load(){return this;}};
Object.defineProperty(document,'fonts',{value:{check:()=>true,add(){},ready:Promise.resolve(),load:async()=>[]}});
dom.window.HTMLCanvasElement.prototype.getContext=function(){return createCanvas(Math.max(1,this.width||1),Math.max(1,this.height||1)).getContext('2d');};
const sdk=await import(fileURLToPath(new URL('../../fireatlas/static/studio-assets/excalidraw-sdk.mjs',import.meta.url)));
const ir=JSON.parse(await readFile(process.argv[2],'utf8'));
const raw=sceneSkeletons(ir),created=sdk.convertToExcalidrawElements(raw.elements,{regenerateIds:false});
const elements=sdk.restoreElements(created,null,{repairBindings:true});
await writeFile(process.argv[3],sdk.serializeAsJSON(elements,{viewBackgroundColor:'#fbf7ef'},raw.files,'local'));
await writeFile(process.argv[4],JSON.stringify(raw.mapping));
dom.window.close();
