#!/usr/bin/env python3
"""Render the local, silent 90-second perfected-plan evidence sequence.

This is a capture aid, not a deployment or a scientific result.  Every image is
an inspected frame from the local static bundle; the globe frame is preserved
from the existing project and is not regenerated by this script.
"""

from __future__ import annotations

import json
import hashlib
import shutil
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FRAMES = ROOT / "docs" / "winning-plan" / "evidence" / "video-frames"
OUTPUT = ROOT / "docs" / "winning-plan" / "evidence" / "FireAtlas_90s_perfected_demo.mp4"
MANIFEST = ROOT / "docs" / "winning-plan" / "evidence" / "FireAtlas_90s_perfected_demo.manifest.json"
CAPTIONS = ROOT / "docs" / "winning-plan" / "evidence" / "FireAtlas_90s_perfected_demo.vtt"
STATIC_MANIFEST = ROOT / "site" / "data" / "v2" / "manifest.json"
FPS = 30
WIDTH = 1600
HEIGHT = 900

SCENES = (
    {"image": "01-globe-home.png", "duration": 5,
     "label": "01 / SEE · EXISTING GLOBE + CONTROLS",
     "title": "NASA satellites watched fire activity for decades.",
     "subtitle": "The record changes when the sensor changes; the FireAtlas globe remains the entry point."},
    {"image": "07-norcal-bridge.png", "duration": 10,
     "label": "02 / COMPARE · VISIBLE SENSOR BRIDGE",
     "title": "Same grid. Separate evidence.",
     "subtitle": "MODIS and VIIRS stay native; centroids group once per UTC day on a common 1 km grid."},
    {"image": "02-norcal-calendar.png", "duration": 20,
     "label": "03 / NORTHERN CALIFORNIA · JULY 2024",
     "title": "The calendar shows its evidence state.",
     "subtitle": "Only 1 comparable year; documented gaps are estimates or unknown, never silent zeros."},
    {"image": "08-norcal-source-drawer.png", "duration": 15,
     "label": "04 / VERIFY · ORIGINAL NASA ROWS",
     "title": "Open the source record behind one day.",
     "subtitle": "UTC acquisition time, native confidence, product version, FRP, and the NASA notice remain inspectable."},
    {"image": "05-punjab-calendar.png", "duration": 15,
     "label": "05 / COMPARE · PUNJAB–HARYANA",
     "title": "The same controls show another fire regime.",
     "subtitle": "Official context is separate; thermal detections do not identify crop-burning cause."},
    {"image": "10-grove-method-audit.png", "duration": 15,
     "label": "06 / VALIDATE · NATIVE MASK AUDIT",
     "title": "A checked match is visible before the claim.",
     "subtitle": "20/20 native granules, 7/7 FIRMS rows matched, and independent review still pending."},
    {"image": "09-norcal-share-card.png", "duration": 10,
     "label": "07 / SHARE · TRACEABLE EVIDENCE",
     "title": "Value, state, version, hash, and limit in one card.",
     "subtitle": "Local static evidence bundle · public URL and independent review remain open gates."},
)


def _textfile(directory: Path, name: str, value: str) -> Path:
    path = directory / f"{name}.txt"
    path.write_text(value, encoding="utf-8")
    return path


def _drawtext(font: str, textfile: Path, color: str, size: int, x: int, y: int) -> str:
    return (f"drawtext=fontfile={font}:textfile={textfile}:expansion=none:"
            f"fontcolor={color}:fontsize={size}:x={x}:y={y}")


def _verify_video(path: Path) -> None:
    probe = shutil.which("ffprobe")
    if not probe:
        raise RuntimeError("ffprobe is required to verify the rendered video")
    result = subprocess.run(
        [probe, "-v", "error", "-show_entries",
         "format=duration:stream=codec_name,codec_type,width,height,r_frame_rate",
         "-of", "json", str(path)], check=True, capture_output=True, text=True,
    )
    data = json.loads(result.stdout)
    streams = data.get("streams", [])
    video = [stream for stream in streams if stream.get("codec_type") == "video"]
    audio = [stream for stream in streams if stream.get("codec_type") == "audio"]
    duration = float(data["format"]["duration"])
    if (len(video) != 1 or audio or video[0].get("codec_name") != "h264"
            or video[0].get("width") != WIDTH or video[0].get("height") != HEIGHT
            or video[0].get("r_frame_rate") != "30/1" or abs(duration - 90.0) > 0.1):
        raise RuntimeError(f"Unexpected video properties: {data}")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write_manifest(video: Path) -> Path:
    """Bind the local rehearsal to the exact frames and source bundle capture.

    The manifest is presentation provenance only. It does not turn a local
    rehearsal into a public deployment or a scientific validation result.
    """
    if not CAPTIONS.is_file():
        raise FileNotFoundError(f"caption sidecar is missing: {CAPTIONS}")
    if not STATIC_MANIFEST.is_file():
        raise FileNotFoundError(f"static bundle manifest is missing: {STATIC_MANIFEST}")
    MANIFEST.write_text(json.dumps({
        "schema": "fireatlas-video-rehearsal-v1",
        "video": {"path": video.relative_to(ROOT).as_posix(),
                  "sha256": _sha256(video), "width": WIDTH, "height": HEIGHT,
                  "fps": FPS, "duration_seconds": 90, "audio": False},
        "frames": [{"path": (FRAMES / scene["image"]).relative_to(ROOT).as_posix(),
                    "sha256": _sha256(FRAMES / scene["image"]),
                    "duration_seconds": scene["duration"], "label": scene["label"]}
                   for scene in SCENES],
        "scope": "local static-bundle rehearsal with a timed WebVTT sidecar; public URL, voice-over, and outside-user review remain open",
        "captions": {"path": CAPTIONS.relative_to(ROOT).as_posix(),
                     "sha256": _sha256(CAPTIONS), "format": "WebVTT",
                     "timed_to_scenes": True},
        "static_bundle": {"path": STATIC_MANIFEST.relative_to(ROOT).as_posix(),
                          "sha256": _sha256(STATIC_MANIFEST)},
        "globe": "existing frame retained; this script does not render or edit globe assets",
    }, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return MANIFEST


def render() -> Path:
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        raise RuntimeError("ffmpeg is required to render the video")
    missing = [FRAMES / scene["image"] for scene in SCENES if not (FRAMES / scene["image"]).is_file()]
    if missing:
        raise FileNotFoundError(", ".join(map(str, missing)))
    font_head = ROOT / "fireatlas/static/fonts/space-grotesk.ttf"
    font_body = ROOT / "fireatlas/static/fonts/dm-sans.ttf"
    if not font_head.is_file() or not font_body.is_file():
        raise FileNotFoundError("project fonts are missing")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="fireatlas-perfected-video-") as temp:
        temporary = Path(temp)
        command = [ffmpeg, "-hide_banner", "-loglevel", "error", "-nostdin", "-y"]
        filters: list[str] = []
        labels: list[str] = []
        for index, scene in enumerate(SCENES):
            duration = scene["duration"]
            command += ["-f", "lavfi", "-i", f"color=c=0x07131c:s={WIDTH}x{HEIGHT}:r={FPS}:d={duration}"]
            background = f"bg{index}"
            filters.append(f"[{index * 2}:v]fps={FPS},format=rgba[{background}]")
            command += ["-loop", "1", "-framerate", str(FPS), "-t", str(duration), "-i", str(FRAMES / scene["image"])]
            image = f"img{index}"
            filters.append(f"[{index * 2 + 1}:v]fps={FPS},scale=1440:810:force_original_aspect_ratio=decrease,pad=1440:810:(ow-iw)/2:(oh-ih)/2:color=0x07131c,setsar=1,format=rgba[{image}]")
            composed = f"composed{index}"
            filters.append(f"[{background}][{image}]overlay=80:16:shortest=1,drawbox=x=79:y=15:w=1442:h=812:color=0x344b58:t=1,drawbox=x=80:y=832:w=1440:h=1:color=0x263c4a:t=fill[{composed}]")
            label = _textfile(temporary, f"scene-{index}-label", scene["label"])
            title = _textfile(temporary, f"scene-{index}-title", scene["title"])
            subtitle = _textfile(temporary, f"scene-{index}-subtitle", scene["subtitle"])
            progress = []
            for progress_index in range(len(SCENES)):
                x = 80 + progress_index * 207
                color = "0xf39a68" if progress_index == index else "0x2a3c46"
                progress.append(f"drawbox=x={x}:y=897:w=198:h=3:color={color}:t=fill")
            caption = f"caption{index}"
            filters.append(f"[{composed}]" + ",".join((
                _drawtext(str(font_body), label, "0xf4a071", 12, 80, 837),
                _drawtext(str(font_head), title, "0xf2f5f5", 24, 80, 851),
                _drawtext(str(font_body), subtitle, "0xa5b7bf", 15, 80, 880),
                *progress,
            )) + f"[{caption}]")
            zoomed = f"zoomed{index}"
            filters.append(f"[{caption}]zoompan=z='min(zoom+0.00005,1.015)':d=1:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s={WIDTH}x{HEIGHT}:fps={FPS},trim=duration={duration},setpts=PTS-STARTPTS,format=yuv420p[{zoomed}]")
            labels.append(f"[{zoomed}]")
        filters.append(f"{''.join(labels)}concat=n={len(SCENES)}:v=1:a=0,fps={FPS},format=yuv420p[outv]")
        command += ["-filter_complex", ";".join(filters), "-map", "[outv]", "-an", "-t", "90", "-r", str(FPS), "-c:v", "libx264", "-preset", "medium", "-crf", "20", "-movflags", "+faststart", str(OUTPUT)]
        subprocess.run(command, cwd=ROOT, check=True)
    _verify_video(OUTPUT)
    _write_manifest(OUTPUT)
    return OUTPUT


if __name__ == "__main__":
    try:
        print(f"Rendered and verified: {render().relative_to(ROOT)}")
    except (FileNotFoundError, RuntimeError, subprocess.CalledProcessError) as exc:
        raise SystemExit(str(exc)) from exc
