"""Inspect an existing owned native AI& film; never submit another paid job."""
import argparse
import json
import shutil
import subprocess
from pathlib import Path
from playwright.sync_api import sync_playwright, expect


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--identity', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--base', default='http://127.0.0.1:8000')
    args = parser.parse_args()
    identity = json.loads(args.identity.read_text())
    args.output.mkdir(parents=True, exist_ok=True)
    report = {'checks': [], 'page_errors': [], 'generation_posts': 0}
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True, executable_path=shutil.which('chromium'), args=['--autoplay-policy=no-user-gesture-required'])
        context = browser.new_context(viewport={'width':1440,'height':1000}, reduced_motion='reduce')
        base = args.base.rstrip('/')
        response = context.request.post(base+'/api/studio/recover',data={'recovery':identity['recovery']},headers={'Origin':base})
        assert response.ok
        response = context.request.get(base+'/api/studio/renders/'+identity['render'])
        assert response.ok
        job = response.json()
        assert job['status'] == 'completed', job.get('error')
        manifest = job['manifest']
        assert manifest['engine'] == 'aiand-native-video'
        assert manifest['provider']['model'] == 'minimaxai/minimax-h3'
        assert manifest['provider']['clips'] and all(c['video_id'] and c['state']=='downloaded' for c in manifest['provider']['clips'])
        assert manifest['narration']['status'] == 'narrated'
        report['provider'] = {'model':manifest['provider']['model'], 'completed_clips':len(manifest['provider']['clips']),
            'native_resolution':manifest['provider']['native_resolution'], 'quoted_cost_usd':manifest['provider']['quoted_cost_usd'],
            'reused_clips':manifest['provider'].get('reused_clips',0), 'new_submission_cost_usd':manifest['provider'].get('new_submission_cost_usd')}
        path = Path('data/studio/renders')/identity['render']/'briefing.mp4'
        probe = subprocess.run(['ffprobe','-v','error','-show_entries','stream=codec_type,codec_name,width,height,r_frame_rate:format=duration,size','-of','json',str(path)],check=True,capture_output=True,text=True)
        report['media'] = json.loads(probe.stdout)
        assert {s['codec_type'] for s in report['media']['streams']} >= {'video','audio','subtitle'}
        subprocess.run(['ffmpeg','-v','error','-y','-ss','4','-i',str(path),'-frames:v','1',str(args.output/'native-film-frame.png')],check=True,capture_output=True)
        page=context.new_page()
        page.on('pageerror',lambda e:report['page_errors'].append(str(e)))
        def seen(request):
            if request.method=='POST' and ('/renders' in request.url or '/story-generations' in request.url):
                report['generation_posts']+=1
        page.on('request',seen)
        url=base+'/studio.html?board='+identity['board']+'&tab=story'
        for attempt in range(2):
            page.goto(url,wait_until='domcontentloaded')
            video=page.get_by_label('Generated infographic film',exact=True)
            expect(video).to_have_attribute('src', base+'/api/studio/renders/'+identity['render']+'/artifact?name=video',timeout=30000)
            expect(page.get_by_role('progressbar',name='Story creation progress')).to_have_attribute('aria-valuenow','100')
            expect(page.get_by_text('Generated by AI& minimaxai/minimax-h3',exact=False)).to_be_visible()
            page.wait_for_function("document.querySelector('.story-film video')?.readyState >= 1")
            video.evaluate('async v=>{v.currentTime=4;await v.play()}')
            page.wait_for_function("document.querySelector('.story-film video')?.currentTime > 4.25")
            assert video.evaluate('v=>!v.muted && v.volume > 0')
            video.evaluate('v=>v.pause()')
        page.locator('.story-panel').screenshot(path=str(args.output/'native-story-desktop.png'))
        for width in (360,390,768):
            page.set_viewport_size({'width':width,'height':950})
            assert page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'),width
            expect(page.get_by_role('link',name='Download film',exact=True)).to_be_visible()
        report['checks']=['Completed native provider jobs and source clip hashes recorded.',
            'Final MP4 has video, audio and subtitles; actual native film restores at 100%.',
            'Reload retains the native film instead of the older local render.',
            'Actual video plays with sound enabled, without another generation request.',
            '360/390/768 layouts have no horizontal page overflow.']
        assert not report['page_errors'] and not report['generation_posts']
        browser.close()
    (args.output/'acceptance.json').write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps(report,indent=2))


if __name__=='__main__':
    main()
